
notifications:
  email: false

language: python

stages:
  - lint
  - test

python:
  - 3.6
  - 2.7

env:
  - ANSIBLE_VER: 2.5.2
    FOO: 123
  - ANSIBLE_VER: 2.6.1
    FOO: 456

sudo: true

stage: test
script:
  - echo "Test $ANSIBLE_VER ; $FOO"

jobs:
  include:
    - stage: lint
      script:
        - echo "Lint $ANSIBLE_VER ; $FOO"
