
notifications:
  email: false


matrix:
  include:
    - language: node_js
      node_js: "6"
      env:
        - FOO=123
        - FOO=456
      script:
        - echo $FOO
   
    - language: python
      python:
        - 2.7
        - 3.6
      env:
        - BAR=1234
        - BAR=5678
      script:
        - echo $bar
